version: '3'
services:

  server:
    container_name: server
    image: tp1node:latest
    entrypoint: /node blockchain
    environment:
      - ReaderCount=2
    networks:
      - testing_net
    volumes:
      - ./config/blockchain:/etc/distros/config:ro

  service:
    container_name: service
    image: tp1node:latest
    entrypoint: /node service
    environment:
      - BlockchainServerName=server
      - ReaderCount=2
    depends_on:
      - server
    networks:
      - testing_net
    volumes:
      - ./config/service:/etc/distros/config:ro

networks:
  testing_net:
    name: testing_net
    ipam:
      driver: default
      config:
       - subnet: 172.25.125.0/24